services:
  web:
    build: .
    container_name: course_engine_web
    restart: unless-stopped

    networks:
      - web

    labels:
      - 'traefik.enable=true'

      - 'traefik.http.routers.course-engine.rule=Host(`course-engine.gastonlevy.com`)'
      - 'traefik.http.routers.course-engine.entrypoints=web,websecure'
      - 'traefik.http.routers.course-engine.tls.certresolver=le'

      - 'traefik.http.services.course-engine.loadbalancer.server.port=80'

networks:
  web:
    external: true
